### ISSUE TITLE
Payload.py : Syntax error on 'import discord'

### ISSUE THREAD

**Issue by thehorrorevent** [Znunu/Idisagree#1]
botToken = 'BOTTOKENHERE'import discord
^
SyntaxError: invalid syntax

![image](https://user-images.githubusercontent.com/80074052/147892614-6d14bb2c-322d-4c95-aa13-da818ca3a514.png)

**Comment by Znunu** [comment]
sorry for the late reply
could you send the full stacktrace/error ?
